package models

// AllowedTables maps table names to a boolean indicating if they are allowed for generic CRUD operations.
var AllowedTables = map[string]bool{
	"categories":          true,
	"blogs":               true,
	"users":               true,
	"pages":               true,
	"customers":           true,
	"settings":            true,
	"products":            true,
	"attributes":          true,
	"options":             true,
	"coupons":             true,
	"orders":              true,
	"languages":           true,
	"currencies":          true,
	"countries":           true,
	"states":              true,
	"districts":           true,
	"tax_classes":         true,
	"tax_rates":           true,
	"zones":               true,
	"blog_categories":     true,
	"filters":             true,
	"inventories":         true,
	"inventory_adjusts":   true,
	"inventory_histories": true,
	"newsletters":         true,
	"payment_methods":     true,
	"plugins":             true,
	"purchases":           true,
	"purchase_returns":    true,
	"reviews":             true,
	"roles":               true,
	"transactions":        true,
	"warehouses":          true,
	"suppliers":           true,
	"transfers":           true,
	"adjustments":         true,
	"expenses":            true,
}
